# Generated by Django 3.2.10 on 2022-01-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/media/defaults/categories_no_img.png', upload_to='categories/%Y/%m/%d'),
        ),
    ]
