# Generated by Django 3.2.10 on 2022-01-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, default='defaults/categories_no_img.png', upload_to='categories/%Y/%m/%d'),
        ),
    ]
