# Generated by Django 3.2.10 on 2022-01-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220121_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Man', 'man'), ('Woman', 'woman')], default='woman', max_length=20),
            preserve_default=False,
        ),
    ]
