# Generated by Django 3.2.10 on 2022-01-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('discount', models.IntegerField()),
                ('percentage', models.BooleanField(default=False)),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Coupons',
            },
        ),
    ]
