# Generated by Django 3.2.10 on 2022-01-27 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertrackingstatus',
            name='Order',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='order_tracking_status', to='orders.order'),
            preserve_default=False,
        ),
    ]
