# Generated by Django 3.2.10 on 2022-01-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordertrackingstatus_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertrackingstatus',
            name='order_tacking',
        ),
        migrations.DeleteModel(
            name='OrderTracking',
        ),
    ]
